name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code & Configure Env Var
        uses: actions/checkout@v2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and package Spring application
        run: ./gradlew clean assemble

      - name: Build Docker image
        run: docker build -t pickleddict/spring-todolist-backend .

      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push pickleddict/spring-todolist-backend

      - name: Deploy to EC2
        run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -i ec2_key.pem ${{ secrets.EC2_LOGIN_STRING }} "docker stop spring-todo-backend"
          ssh -i ec2_key.pem ${{ secrets.EC2_LOGIN_STRING }} "docker rm spring-todo-backend"
          ssh -i ec2_key.pem ${{ secrets.EC2_LOGIN_STRING }} "docker pull pickleddict/spring-todolist-backend"
          ssh -i ec2_key.pem ${{ secrets.EC2_LOGIN_STRING }} "docker run -d --name spring-todo-backend -p 8080:8080 pickleddict/spring-todolist-backend"